name = "AsteroidCatcher"
uuid = "592dbf9c-5a5d-4be0-98d7-6e4092662be4"
authors = ["Santeri Väätäjä"]
version = "1.0.0-DEV"

[compat]
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
